In [2]:
import numpy as np

In [3]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr.reshape(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr.reshape(3*4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
x=np.arange(3)

In [11]:
x#x는 1차원 배열

array([0, 1, 2])

In [16]:
x.reshape(1,3) # x는 2차원배열(행렬, 1*3)

array([[0, 1, 2]])

In [17]:
x.reshape(3,1) # x는 2차원배열(행렬, 3*1)

array([[0],
       [1],
       [2]])

In [21]:
x[:, np.newaxis].shape

(3, 1)

In [23]:
arr=arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr=arr.reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
for i in arr:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [26]:
for i in arr:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [27]:
arr=arr.reshape(2,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [28]:
for i in arr:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11


In [30]:
# 파이썬 : 리스트, 튜플, 딕셔너리, 집합
# 넘파이 : 배열(ndarray)
# 판다스 : 데이터프레임, 시리즈
# 데이터 수집(크롤링, db) -> 전처리(넘파이, 판다스) -> 분석(판다)
# 컬러이미지 : 1000*1000*3   *10만장
# [
#     [
#         [200 0 0 255 255 255 0 0 0...255],
#         [200 0 0 255 255 255 0 0 0...255],
#         ...
#         [200 0 0 255 255 255 0 0 0...255]
#     ],
#     [
#         [200 0 0 255 255 255 0 0 0...255],
#         [200 0 0 255 255 255 0 0 0...255],
#         ...
#         [200 0 0 255 255 255 0 0 0...255]
#     ],
#     [
#         [200 0 0 255 255 255 0 0 0...255],
#         [200 0 0 255 255 255 0 0 0...255],
#         ...
#         [200 0 0 255 255 255 0 0 0...255]
#     ]
# ]
#    /255

In [31]:
a1=np.ones((2,3))

In [32]:
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
a2=np.zeros((3,3))

In [43]:
a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.hstack([a1,a2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [45]:
np.vstack([a1,a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
# dstack(depth) : 행, 열이 아닌 깊이 방향으로 배열을 합침

In [48]:
a1=np.ones((3,4))
a2=np.zeros((3,4))

In [49]:
a1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
#3*4*2
np.dstack([a1,a2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [52]:
np.dstack([a1,a2]).shape

(3, 4, 2)

In [53]:
# dstack([a1,a2]) => 2개의 3*4 배열 => 1개의 3*4*2 배열

In [54]:
# dstack은 잘사용 하지 않고 , stack을 사용함

In [56]:
np.stack([a1,a2])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [58]:
np.stack([a1,a2]).shape
#2개의 3*4 => 1개의 2*3*4

(2, 3, 4)

In [69]:
r1=np.stack([a1,a2], axis=1)

In [70]:
r1.shape

(3, 2, 4)

In [71]:
r2=np.stack([a1,a2], axis=2)
r2.shape

(3, 4, 2)

In [72]:
# 두 행렬 (3,4), (3,4)를 stack함수로 연결할 때 axis값에 따라 shape이 달라짐
# axis=0 => 2,3,4
# axis=1 => 3,2,4
# axis=2 => 3,4,2

In [73]:
a1=np.array([1,2,3])
a2=np.array([11,12,13])

In [74]:
np.hstack([a1,a2])

array([ 1,  2,  3, 11, 12, 13])

In [76]:
np.r_[a1,a2] # 특별한 함수, 인덱서 함수, r(row)

array([ 1,  2,  3, 11, 12, 13])

In [77]:
np.c_[a1,a2] # 특별한 함수, 인덱서 함수, c(column)

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [78]:
np.vstack([a1,a2])

array([[ 1,  2,  3],
       [11, 12, 13]])

In [80]:
# tile: 동일한 배열을 반복해서 연결
arr=np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
np.tile(arr,3) #좌우로 3번반복

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [86]:
np.tile(arr,(3,1)) # 위아래로 3번 반복, 좌우로 1번반복

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [87]:
np.tile(arr,(3,2)) # 위아래로 3번 반복, 좌우로 2번반복

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
arr1=np.ones((3,2))

arr2=np.zeros((3,3))

np.hstack([arr2,arr1])

In [97]:
x=np.arange(3)
y=np.arange(5)
# (x,y)=(0,0),(0,1)..(0,4),(1,0),...(1,4),(2,0)...(2,4)

In [98]:
x

array([0, 1, 2])

In [99]:
y

array([0, 1, 2, 3, 4])

In [101]:
x,y=np.meshgrid(x,y)

In [102]:
x

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [103]:
y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [104]:
[list(zip(x,y)) for x,y in zip(x,y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [105]:
arr1=np.array([1,2,3])

In [106]:
arr2=np.array([11,21,31])

In [107]:
np.concatenate([arr1,arr2])

array([ 1,  2,  3, 11, 21, 31])

In [108]:
np.concatenate((arr1,arr2))

array([ 1,  2,  3, 11, 21, 31])

In [115]:
np.arange(0,6)
np.arange(10,16)
np.arange(20,26)

array([0, 1, 2, 3, 4, 5])

In [120]:
for i in range(6):
    arr=np.arange(0+i*10,6+i*10))

In [121]:
res

array([50, 51, 52, 53, 54, 55])

In [122]:
import numpy as np

arrays = []
for i in range(6):
    arr = np.arange(0 + i * 10, 6 + i * 10)
    arrays.append(arr)

In [123]:
arrays

[array([0, 1, 2, 3, 4, 5]),
 array([10, 11, 12, 13, 14, 15]),
 array([20, 21, 22, 23, 24, 25]),
 array([30, 31, 32, 33, 34, 35]),
 array([40, 41, 42, 43, 44, 45]),
 array([50, 51, 52, 53, 54, 55])]

In [127]:
arrays = []
for i in range(6):
    arr = np.arange(0 + i * 10, 6 + i * 10)
    arrays.append(arr)

res = np.concatenate(arrays)
res.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [128]:
a=np.arange(1,5)
b=np.array([4,2,2,4])

In [129]:
a

array([1, 2, 3, 4])

In [130]:
b

array([4, 2, 2, 4])

In [131]:
a>=b

array([False,  True,  True,  True])

In [132]:
np.all(a>=b) # 각 요소들을 일일이 비교하는게 아니라, 배열의 모든 요소에 대해 조건을 만족하는지

False

In [133]:
# 벡터(행렬)끼리 연산하려면 크기가 동일해야함
# 브로드캐스팅: 벡터(행렬)의 크기가 다르더도 연산이 가능하도록 
# 크기를 동일하게 해주는 작업
벡터     스칼라
1                      11
2    +    10   =       12
3                      13
4                      14

In [142]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [135]:
y=10

In [136]:
x+y

array([11, 12, 13, 14])

In [ ]:
행렬         벡터
0 1 2        10
1 2 3     +  11
3 4 5        12

In [ ]:
행렬(2)    벡터(1)->행렬(2)
0 1 2      10 10 10    10 11 12
1 2 3  +   11 11 11 =     ...
3 4 5      12 12 12

In [ ]:
행렬(2)    벡터(1)->행렬(2)
0 1 2      10 11 12    
1 2 3  +   10 11 12 =     ...
3 4 5      10 11 12

In [143]:
y=np.ones_like(x)

In [145]:
np.arange(3)

array([1, 2, 3])

In [146]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [149]:
x,y=np.meshgrid(np.arange(3),np.arange(5))
x+y

In [150]:
x+y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [152]:
[range(7)[i:i+3] for i in range(5)]

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [153]:
np.vstack([range(7)[i:i+3] for i in range(5)])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [156]:
import numpy as np

arr = np.zeros((5, 5), dtype=int)

#짝수행
for i in range(0, 5, 2):
    arr[i] = np.arange(1 + i * 5, 6 + i * 5)

#홀수행
for i in range(1, 5, 2):
    arr[i] = np.arange(1 + i * 5, 6 + i * 5)[::-1]

arr

array([[ 1,  2,  3,  4,  5],
       [10,  9,  8,  7,  6],
       [11, 12, 13, 14, 15],
       [20, 19, 18, 17, 16],
       [21, 22, 23, 24, 25]])