In [1]:
import numpy as np
import time

In [2]:
#파이썬 리스트
li=[1, '가', True, [1,2],{'a':1}]
li

[1, '가', True, [1, 2], {'a': 1}]

In [3]:
'''
넘파이(배열)과 파이썬 (리스트) 차이
배열 : 모든 자료형이 동일, 데이터의 개수를 변경할 수 없다
파이썬에서 배열을 기본저긍로 제공하지 않으므로, 별도로 넘파이 패키지를 설치하여 배열을 사용

벡터: 숫자를 원소로 갖는 리스트(배열), 행벡터, 열벡터
행벡터: x=[x1 x2 ... xn]
공간에서의 한 점
원점으로부터 떨어진 상대적 위치

5차원벡터: 5차원 공간에 표현된 한 점
[[5 2 0 0 3] #행벡터
[1 3 2 3 0]
....]

[5]  #열벡터
|1|
|0|
|0|
[3]
행렬: 벡터를 원소로 갖는 2차원 배열
공간에서의 여러 점(데이터 모임)

'''

'\n넘파이(배열)과 파이썬 (리스트) 차이\n배열 : 모든 자료형이 동일, 데이터의 개수를 변경할 수 없다\n파이썬에서 배열을 기본저긍로 제공하지 않으므로, 별도로 넘파이 패키지를 설치하여 배열을 사용\n\n벡터: 숫자를 원소로 갖는 리스트(배열), 행벡터, 열벡터\n행벡터: x=[x1 x2 ... xn]\n공간에서의 한 점\n원점으로부터 떨어진 상대적 위치\n\n5차원벡터: 5차원 공간에 표현된 한 점\n[[5 2 0 0 3] #행벡터\n[1 3 2 3 0]\n....]\n\n[5]  #열벡터\n|1|\n|0|\n|0|\n[3]\n행렬: 벡터를 원소로 갖는 2차원 배열\n공간에서의 여러 점(데이터 모임)\n\n'

In [4]:
pip list

Package                           Version
--------------------------------- ------------
aiobotocore                       2.7.0
aiohttp                           3.9.3
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.12
altair                            5.0.1
anaconda-anon-usage               0.4.3
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.1.4
anaconda-navigator                2.5.2
anaconda-project                  0.11.1
anyio                             4.2.0
appdirs                           1.4.4
archspec                          0.2.1
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           5.3.4
asttokens                         2.0.5
async-lru                         2.0.4
atomicwrites             

In [5]:
x=[10,20,30]  #리스트
x

[10, 20, 30]

In [6]:
array_x=np.array(x)  #배열

In [7]:
array_x

array([10, 20, 30])

In [8]:
type(array_x)

numpy.ndarray

In [9]:
'''
사과:1000, 딸기:2000, 배:2000, 파인애플:5000, 바나나:3000
5/1 사과:5 딸기:2 바나나:3

덧셈, 뺄셈
[5 2 0 0 3] + [1 3 2 3 0]= [6 5 2 3 3]
'''

'\n사과:1000, 딸기:2000, 배:2000, 파인애플:5000, 바나나:3000\n5/1 사과:5 딸기:2 바나나:3\n\n덧셈, 뺄셈\n[5 2 0 0 3] + [1 3 2 3 0]= [6 5 2 3 3]\n'

In [10]:
s=time.time()
data=list(range(1,10000000))
#data
ans=[2*i for i in data]
e=time.time()
ans
print(e-s)

0.4951345920562744


In [11]:
arr_data=np.array(data)
arr_data

array([      1,       2,       3, ..., 9999997, 9999998, 9999999])

In [12]:
s=time.time()
ans2=2*arr_data  #벡터화 연산
e=time.time()
ans2
print(e-s)

0.012293577194213867


In [13]:
x=[1,2]
y=[3,4] 
x+y#파이썬 연산

[1, 2, 3, 4]

In [14]:
np.array(x)+np.array(y)

array([4, 6])

In [15]:
#1~100 수 중에서 짝수를 even, 홀수를 odd에 저장한 다음
#같은 위치의 요소끼리 비교하여 큰 갑을 출력

In [16]:
even=[e for e in range(1,101) if e%2==0]
odd=[o for o in range(1,101) if o%2==1]

for i in range(50):
    if even[i] > odd[i]:
        print(even[i])
    else:
        print(odd[i])

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [17]:
even=[e for e in range(1,101) if e%2==0]
odd=[o for o in range(1,101) if o%2==1]
a_even=np.array(even)
a_odd=np.array(odd)

In [18]:
a_even+a_odd
a_even>50
a_even==10
(a_even>30) & (a_even%5==0)

a_even[a_even>a_odd]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [19]:
np.__version__

'1.26.4'

In [20]:
np.array((10,20,30))

array([10, 20, 30])

In [21]:
# 0차원 배열 = 스칼라 = 배열의 각 요소 값
arr=np.array(10)
arr

array(10)

In [22]:
#1차원 배열 = 0차원 배열을 요소로 갖는 배열
arr=np.array([10,20,30])
arr

array([10, 20, 30])

In [23]:
#2차원 배열 = 1차원 배열을 요소로 갖는 배열 = 행렬
arr=np.array([[10,20,30],[40,50,60]])
arr # 2행3열
len(arr)#행
len(arr[0])#열

3

In [24]:
# 3차원배열 = 2차원 배열을 요소로 갖는 배열
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr
arr.ndim #몇차원인지

3

In [25]:
len(arr[0][0])

3

In [26]:
len(arr) #깊이
len(arr[0])#행
len(arr[0][0]) #열
arr=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])

In [27]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [28]:
arr=np.array(list(range(1,25)))

In [29]:
arr_re=arr.reshape(2,3,4)
arr_re

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [30]:
arr_re.ndim
arr_re.shape

(2, 3, 4)

In [31]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [32]:
arr[0]

1

In [33]:
# 2차원배열 생성
data=[a for a in range(11,21)]
arr=(np.array(data)).reshape(2,5)

In [34]:
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
arr[1]

array([16, 17, 18, 19, 20])

In [36]:
# 1~12요소로 초기화, 3차원배열
data=[range(1,13)]
arr=(np.array(data)).reshape(2,2,3)

In [37]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr[0][1][2]

6

In [39]:
arr=np.array(list(range(1,8)))
arr

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
arr[::2]

array([1, 3, 5, 7])

In [41]:
arr=np.array(list(range(11,41))).reshape(6,5)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [42]:
arr[-2,-2]

34

In [43]:
arr[2][:3]

array([21, 22, 23])

In [44]:
arr[1:3,1:4]

array([[17, 18, 19],
       [22, 23, 24]])

In [45]:
pip install FinaceDataReader

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement FinaceDataReader (from versions: none)
ERROR: No matching distribution found for FinaceDataReader


In [46]:
pip install -U finance-datareader

Note: you may need to restart the kernel to use updated packages.


In [54]:
kakao_arr=np.loadtxt('kakao_pre.csv', skiprows=1, dtype=np.float32, delimiter=',')

In [56]:
kakao_arr[:5]
kakao_arr[:,0]

array([58000., 57200., 57500., 57800., 57100., 56400., 56200., 56500.,
       56700., 55900., 58200., 57400., 57900., 58100., 57500., 56600.,
       56400., 57000., 56500., 56300., 56300., 57600., 57700., 57000.,
       56800., 56900., 57000., 56400., 55700., 54300., 53400., 52400.,
       51700., 50200., 50200., 49000., 50000., 49700., 49000., 48850.,
       49300., 50900., 49950., 48850., 50600., 49850., 50100., 50700.,
       52000., 52300., 52400., 52700., 51800., 50100., 50000., 50100.,
       49600., 48800., 47500., 50200., 50900., 51800., 55100., 52800.,
       53800., 51700., 53500., 52100., 52300., 51400., 51700., 50300.,
       50000., 48650., 48500., 48550., 48700., 49450., 48000., 48550.,
       48000., 49150., 49000., 47950., 48900., 49100., 49000., 48700.,
       48650., 48250., 48200., 48100., 47850., 48100., 48550., 48600.,
       47850., 46800., 45100., 44900., 44650., 43150., 43050., 41750.,
       40600., 42100., 41900., 42700., 43250., 43250., 43400., 42400.,
      