In [10]:
import numpy as np
import random

In [3]:
data=np.random.randint(5, 11, size=10)

In [4]:
np.unique(data)

array([ 5,  6,  7,  8,  9, 10])

In [5]:
np.unique(data, return_counts=True)

(array([ 5,  6,  7,  8,  9, 10]), array([1, 3, 1, 3, 1, 1], dtype=int64))

In [6]:
np.unique(data, return_counts=True)[0]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
np.unique(data, return_counts=True)[1]

array([1, 3, 1, 3, 1, 1], dtype=int64)

In [8]:
np.bincount(data, minlength=11)
# minlength: 0부터 설정된 값-1 까지 수를 범위로 설정하여 빈도수 조사
# minlength=11 이면 0부터 10 까지 수를 범위로 설정하여 빈도수 조사

array([0, 0, 0, 0, 0, 1, 3, 1, 3, 1, 1], dtype=int64)

In [9]:
data

array([ 6,  8,  7,  8,  5,  9, 10,  6,  6,  8])