In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
arr.dtype

dtype('int32')

In [4]:
type(arr)

numpy.ndarray

In [6]:
type(arr[0])

numpy.int32

In [ ]:
1MB =100만 바이트
1GB=10억 바이트
32GB=320억 바이트  => 20GB 여유
200억 / 4 = 50억개 정수를 저장

In [10]:
arr=np.array(['APPLE', 'CHERRY', 'BANANA'])
arr.dtype

dtype('<U5')

In [9]:
#<U6 ? unicode

In [12]:
arr=np.array([1,2,3], dtype=np.float64) #64bit
arr.dtype

dtype('float64')

In [15]:
arr=np.array([1,2,3], dtype=np.float16) #16bit
arr.dtype

dtype('float16')

In [16]:
arr=np.array([1,2,3], dtype=np.int16) #16bit: -3천만~+3천만
arr.dtype

dtype('int16')

In [17]:
arr=np.array([1,2,3], dtype=np.int8) #8bit:-128~127
arr.dtype

dtype('int8')

In [18]:
arr=np.array([1,2,3], dtype=np.float64) #64bit
arr.dtype
#64비트 float 수의 범위 = 4.9 * 10의 -324승 ~ 1.79 * 10의 308승
#32비트 float 수의 범위 = 1.4 * 10의 -45승 ~ 3.4 * 10의 38승

#32비트 int 수의 범위 = -21억 ~ +21억
#64비트 int 수의 범위 = -922경 ~ +922경

dtype('float64')

In [19]:
arr

array([1., 2., 3.])

In [28]:
arr=np.array([1,2,3, -129], dtype=np.int8) #8bit:-128~127

C:\Users\TECH09-01\AppData\Local\Temp\ipykernel_9120\2312191867.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr=np.array([1,2,3, -129], dtype=np.int8) #8bit:-128~127


In [29]:
arr

array([  1,   2,   3, 127], dtype=int8)

In [33]:
arr=np.array([1,2,3], dtype='i2') #i바이트수
arr

array([1, 2, 3], dtype=int16)

In [35]:
arr=np.array([1,2,3])
arr
arr.dtype

dtype('int32')

In [36]:
farr=arr.astype(np.float32)
farr

array([1., 2., 3.], dtype=float32)

In [37]:
farr2=np.array([1,2,3], dtype=np.float32)
farr2

array([1., 2., 3.], dtype=float32)

In [40]:
#arr = np.array([1,2,3, -129], dtype=np.int8)
arr
#구글링 : 2의보수 연산

array([  1,   2,   3, 127], dtype=int8)

In [41]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [43]:
myList=[1,2,'3']
myList

[1, 2, '3']

In [46]:
type(myList)
type(myList[0])
type(myList[2])

str

In [47]:
imyList=[1,2,3]
cmyList=[1,2,'3']

In [50]:
np.array(imyList)

array([1, 2, 3])

In [51]:
np.array(cmyList)
배열 : 동일한 타입(크기도 같고)의 데이터를 여러개 나열한 것

array(['1', '2', '3'], dtype='<U11')

In [53]:
arr1=np.array(list(range(10,14))).reshape(2,2)
arr2=np.array(list(range(10,14))).reshape(2,2)

In [54]:
arr1
arr2

array([[10, 11],
       [12, 13]])

In [55]:
arr1-arr2 #넘파이 배열은 요소간 연산 => 동일한 크기의 배열

array([[0, 0],
       [0, 0]])

In [57]:
arr1*2 #숫자와 연산을 할때는 모든 항목에 동일한 연산

array([[20, 22],
       [24, 26]])

In [58]:
arr1*arr2 #주의:행렬의 곱셈(matrix multiply, matmul)이 아님, 
#요소간 곱셈(element-wise product)

array([[100, 121],
       [144, 169]])

In [61]:
arr1=np.array(list(range(10,14))).reshape(2,2)
arr1

array([[10, 11],
       [12, 13]])

In [62]:
arr2=np.array(list(range(13,17))).reshape(2,2)
arr2

array([[13, 14],
       [15, 16]])

In [64]:
arr1>arr2
arr1>10

array([[False,  True],
       [ True,  True]])

In [65]:
arr1==arr2

array([[False, False],
       [False, False]])

In [66]:
~(arr1==arr2) #~는 not 연산자

array([[ True,  True],
       [ True,  True]])

In [67]:
arr1!=arr2 #같지 않다 !=

array([[ True,  True],
       [ True,  True]])

In [71]:
arr1==arr2
~(arr1==arr2)

array([[ True,  True],
       [ True,  True]])

In [73]:
arr1!=arr2
~(arr1!=arr2)

array([[False, False],
       [False, False]])

In [74]:
(~(arr1==arr2)) | (~(arr1!=arr2))
#     행렬      OR       행렬   => 요소간 OR연산
#OR연산자는 둘 중 하나 이상이 TRUE -> TRUE

array([[ True,  True],
       [ True,  True]])

In [75]:
np.arange(8) #np.array(list(range(8)))

array([0, 1, 2, 3, 4, 5, 6, 7])

In [76]:
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [77]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# 1~24까지의 값, 2*3*4 행렬
# arange, range

np.arange(1, 25).reshape(2, 3, 4)
np.array(range(1, 25)).reshape(2, 3, 4)

In [80]:
data=np.arange(200)
data
data2=data.reshape(4, -1)
data2.shape

(4, 50)

In [82]:
data3=data.reshape(8, -1)
data3

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
        138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174],
      

In [83]:
data4=data.reshape(-1, 10)
data4

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [84]:
arr

array([1, 2, 3])

In [87]:
data.reshape(-1, 5, 10) # 4*5*10
data.reshape(4, -1, 10) 

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]],

       [[150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 

In [ ]:
# 2차원 배열
# 10부터 시작하여 2씩 증가시킨 값으로 초기화
# shape은 3행 4열

In [92]:
np.arange(10,35,2).reshape(3,4)

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [ ]:
# 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34 
# => 13개 data 3,4로 reshape 불가

In [100]:
#불린참조(팬시)

arr=np.array([1,2,3,4])
idx=np.array([True, False, False, True])

In [101]:
arr[idx]

array([1, 4])

In [104]:
np.min(arr)
np.max(arr)

4

In [115]:
arr[np.array([True, False, False, True])]

array([1, 4])

In [116]:
arr[(arr==np.min(arr)) | (arr==np.max(arr))]

array([1, 4])

In [107]:
#python list
# myList=[1,2,3,4]
# for i in myList:
#     if i==1:
#         print(True)
#     else:
#         print(False)

True
False
False
False


In [118]:
#11~20까지의 수가 저장된 배열 arr을 생성하시오.
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [119]:
arr % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [120]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [121]:
arr[arr % 2 == 0]

array([12, 14, 16, 18, 20])

In [122]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [127]:
arr[1]
arr[1]
#arr[1,3] error
arr[np.array([1,3])]
arr[np.array([1,3,5,7,9])]
arr[np.array([1,3,5,7,9,9,9,9,9,9])]

array([12, 14, 16, 18, 20, 20, 20, 20, 20, 20])

In [128]:
#arr=array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
idx=np.array([0,0,0,1,1,1,3,3,3])

In [129]:
arr[idx] #arr[np.array([0,0,0,1,1,1,3,3,3])]

array([11, 11, 11, 12, 12, 12, 14, 14, 14])

In [132]:
arr=np.arange(10,40).reshape(5,-1)
arr

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [138]:
arr[:] #전체행 추출
arr[:,:] #전체행에 대해 전체열을 추출
arr[:,[True,True,True,False,False,False]]

array([[10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])

In [139]:
idx=np.array([True,True,True,False,False,False])
idx

array([ True,  True,  True, False, False, False])

In [140]:
arr[:,idx]

array([[10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])

In [141]:
arr
#arr에서 1(10~),3(12~),5(14~)번째 열을 출력하시오.

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [142]:
arr[:,[0,2,4]]

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [143]:
arr[:,[True,False,True,False,True,False]]

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [144]:
idx = np.array([True, False, True, False, True, False])
arr[:, idx]

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [145]:
arr[:, np.arange(0, 5, 2)]

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [146]:
arr[:, idx]
arr[:, [0, 2, 4]]
arr[:, np.array([0, 2, 4])]
arr[:, np.arange(0, 5, 2)]

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [149]:
arr

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [148]:
arr[:,[4,1,3,0]]

array([[14, 11, 13, 10],
       [20, 17, 19, 16],
       [26, 23, 25, 22],
       [32, 29, 31, 28],
       [38, 35, 37, 34]])

In [ ]:
arr에서 3번째행, 2번째행, 4번째행 순서로 데이터를 추출하시오.

In [151]:
arr

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [ ]:
array([[22, 23, 24, 25, 26, 27],
       [16, 17, 18, 19, 20, 21],
       [28, 29, 30, 31, 32, 33]])


In [150]:
arr[[2,1,3]]

array([[22, 23, 24, 25, 26, 27],
       [16, 17, 18, 19, 20, 21],
       [28, 29, 30, 31, 32, 33]])

In [153]:
arr[[2,1,3]] #행과 열을 구분하는 컴마가 생략되었을 경우에는 행추출
#arr[ 행 , 열 ]
arr[:,[2,1,3]] #arr의 전체 행에서  [2,1,3]번 열을 추출

array([[22, 23, 24, 25, 26, 27],
       [16, 17, 18, 19, 20, 21],
       [28, 29, 30, 31, 32, 33]])

In [154]:
arr[[2,1,3],:]

array([[22, 23, 24, 25, 26, 27],
       [16, 17, 18, 19, 20, 21],
       [28, 29, 30, 31, 32, 33]])

In [ ]:
# 무한대(infinity) : np.inf
# 숫자아님(not a number) : np.nan

In [156]:
np.array([1])/np.array([0])
np.log(0)

C:\Users\TECH09-01\AppData\Local\Temp\ipykernel_9120\878147698.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([1])/np.array([0])
C:\Users\TECH09-01\AppData\Local\Temp\ipykernel_9120\878147698.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [159]:
#0/0
np.array([0])/np.array([0])

C:\Users\TECH09-01\AppData\Local\Temp\ipykernel_9120\2748191917.py:2: RuntimeWarning: invalid value encountered in divide
  np.array([0])/np.array([0])


array([nan])

In [160]:
np.zeros(3)

array([0., 0., 0.])

In [161]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [162]:
np.zeros((3,2)).dtype

dtype('float64')

In [165]:
np.zeros((3,2), dtype='i')
np.zeros((3,2), dtype='i4')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [164]:
np.zeros((3,2), dtype='i8')

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [166]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [171]:
arr=np.ones((3,2))*2
arr

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [172]:
np.ones_like(arr)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [173]:
np.zeros_like(arr)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [176]:
np.arange(2,31,2).reshape(-1,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

In [177]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [178]:
arr=np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [181]:
#transpose : 전치행렬(행과 열을 바꾼 행렬)
arr.transpose()
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [182]:
arr.transpose().transpose()
arr.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [183]:
#(사과, 배, 딸기)
data=np.array([[1,5,0],
               [5,3,2],
               [1,2,0]])
price=np.array([[2000],
                [5000],
                [8000]])

In [185]:
data.shape #3행 3열
price.shape #3행 1열

(3, 1)

In [186]:
#data배열과 price배열간에 행렬의 곱셈 연산 가능?
data.dot(price) #내적

array([[26000],
       [36000],
       [11000]])

In [187]:
data@price #행렬의 곱셈

array([[26000],
       [36000],
       [11000]])

In [188]:
arr=np.arange(10,15)
arr

array([10, 11, 12, 13, 14])

In [189]:
arr2=arr #데이터를 공유한다는 의미(뷰)

In [190]:
arr2

array([10, 11, 12, 13, 14])

In [192]:
arr2[1]=99
arr2

array([10, 99, 12, 13, 14])

In [193]:
arr

array([10, 99, 12, 13, 14])

In [195]:
arr=np.arange(10,15)
arr3=arr.copy()
arr3

array([10, 11, 12, 13, 14])

In [196]:
arr3[1]=99
arr3

array([10, 99, 12, 13, 14])

In [197]:
arr

array([10, 11, 12, 13, 14])